export const REQUEST_CATEGORY_DATA = "REQUEST_CATEGORY_DATA";
export const REQUEST_CATEGORY_SUCCESS = "REQUEST_CATEGORY_SUCCESS";
export const REQUEST_CATEGORY_FAILURE = "REQUEST_CATEGORY_FAILURE";
export const SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY";
export const REMOVE_OLD_DATA_CATEGORY = "REMOVE_OLD_DATA_CATEGORY";
