export const REQUEST_DATA = "REQUEST_DATA";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAILURE = "REQUEST_FAILURE";
export const SET_SELECTED_GAME = "SET_SELECTED_GAME";
export const CALL_SITE = "CALL_SITE";
export const GET_COMPLETE_GAME_DATA = "GET_COMPLETE_GAME_DATA";